;;; doom-snippets-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from doom-snippets.el

(autoload 'doom-snippets-remove-compiled-snippets "doom-snippets" "\
Delete all .yas-compiled-snippets.el files." t)
(autoload 'doom-snippets-initialize "doom-snippets" "\
Add `doom-snippets-dir' to `yas-snippet-dirs', replacing the default
yasnippet directory.")
(eval-after-load 'yasnippet (lambda nil (doom-snippets-initialize)))

;;; End of scraped data

(provide 'doom-snippets-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; doom-snippets-autoloads.el ends here
