[tools]
golang = "1.21.4"
kubectl = "1.27.0"
python = "3.12.6"
ripgrep = "latest"
fd = "latest"
terraform = "1.3.6"
terragrunt = "0.54.9"
nomad = "latest"
neovim = "0.9.5"
bat = "latest"

[settings]
asdf_compat = false
