tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "praqma/praqma-tap"
tap "seatgeek/formulae"
tap "thoughtbot/formulae"
tap "tidwall/jj"
tap "universal-ctags/universal-ctags"
tap "wallix/awless"
brew "bash"
brew "coreutils"
brew "cowsay"
brew "dialog"
brew "doctl"
brew "exercism"
brew "fortune"
brew "gawk"
brew "git"
brew "global"
brew "gnu-sed"
brew "gnupg"
brew "graphviz"
brew "htop"
brew "hugo"
brew "iproute2mac"
brew "jq"
brew "keychain"
brew "lsd"
brew "luarocks"
brew "make"
brew "mas"
brew "mkcert"
brew "neovim"
brew "nmap"
brew "packer"
brew "pandoc"
brew "pwgen"
brew "redo"
brew "shellcheck"
brew "socat"
brew "stgit"
brew "thoughtbot/formulae/rcm"
brew "tig"
brew "tree"
brew "unrar"
brew "urlview"
brew "watch"
brew "wget"
brew "zlib"
brew "gh"
cask "alfred"
cask "font-fira-code"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "mactex-no-gui"
cask "openzfs"
cask "slack"
cask "spotify"
cask "texmaker"
cask "whatsapp"
cask "wireshark"
cask "zenmap"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
