#!/bin/bash
RUBY=/usr/bin/ruby

echo "This script will delete the dotfiles in $HOME and then copy them, if this is unwanted: press CTRL-C now or hit any key to continue"
echo "It will also build the Command-T C extension"
read -p "$*"
for i in *; do
	if [[ -e $HOME/.$i ]]; then
		rm -fr $HOME/.$i && echo "Removing $HOME/.$i"
	fi
    cp -r $i $HOME/.$i && echo "Copying $i to $HOME/.$i"
done
mkdir -p $HOME/.vim/tmp

cd $HOME/.vim/bundle/command-t/ruby/command-t
$RUBY extconf.rb
make
cd $HOME/.snippets/
rake deploy_local
