;;; consult-flycheck-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from consult-flycheck.el

(autoload 'consult-flycheck "consult-flycheck" "\
Jump to flycheck error." t)

;;; End of scraped data

(provide 'consult-flycheck-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-flycheck-autoloads.el ends here
