;;; evil-quick-diff-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from evil-quick-diff.el

(autoload 'evil-quick-diff "evil-quick-diff" "\
Ediff two regions with evil motion." t)
(autoload 'evil-quick-diff-cancel "evil-quick-diff-cancel" "\
Cancel evil-quick-diff and remove selections." t)
(autoload 'evil-quick-diff-install "evil-quick-diff" "\
Setting evil-quick-diff key bindings.")

;;; End of scraped data

(provide 'evil-quick-diff-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-quick-diff-autoloads.el ends here
