;;; evil-numbers-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from evil-numbers.el

 (autoload 'evil-numbers/inc-at-pt "evil-numbers" nil t)
 (autoload 'evil-numbers/dec-at-pt "evil-numbers" nil t)
 (autoload 'evil-numbers/inc-at-pt-incremental "evil-numbers" nil t)
 (autoload 'evil-numbers/dec-at-pt-incremental "evil-numbers" nil t)

;;; End of scraped data

(provide 'evil-numbers-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-numbers-autoloads.el ends here
