;;; xref-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from xref.el

(autoload 'xref-find-backend "xref")
(define-obsolete-function-alias 'xref-pop-marker-stack #'xref-go-back "29.1")
(autoload 'xref-go-back "xref" "\
Go back to the previous position in xref history.
To undo, use \\[xref-go-forward]." t)
(autoload 'xref-go-forward "xref" "\
Go to the point where a previous \\[xref-go-back] was invoked." t)
(autoload 'xref-marker-stack-empty-p "xref" "\
Whether the xref back-history is empty.")
(autoload 'xref-forward-history-empty-p "xref" "\
Whether the xref forward-history is empty.")
(autoload 'xref-show-xrefs "xref" "\
Display some Xref values produced by FETCHER using DISPLAY-ACTION.
The meanings of both arguments are the same as documented in
`xref-show-xrefs-function'.

(fn FETCHER DISPLAY-ACTION)")
(autoload 'xref-find-definitions "xref" "\
Find the definition of the identifier at point.
With prefix argument or when there's no identifier at point,
prompt for it.

If sufficient information is available to determine a unique
definition for IDENTIFIER, display it in the selected window.
Otherwise, display the list of the possible definitions in a
buffer where the user can select from the list.

Use \\[xref-go-back] to return back to where you invoked this command.

(fn IDENTIFIER)" t)
(autoload 'xref-find-definitions-other-window "xref" "\
Like `xref-find-definitions' but switch to the other window.
If this command needs to split the current window, it by default obeys
the user options `split-height-threshold' and `split-width-threshold',
when it decides whether to split the window horizontally or vertically.

(fn IDENTIFIER)" t)
(autoload 'xref-find-definitions-other-frame "xref" "\
Like `xref-find-definitions' but switch to the other frame.

(fn IDENTIFIER)" t)
(autoload 'xref-find-references "xref" "\
Find references to the identifier at point.
This command might prompt for the identifier as needed, perhaps
offering the symbol at point as the default.
With prefix argument, or if `xref-prompt-for-identifier' is t,
always prompt for the identifier.  If `xref-prompt-for-identifier'
is nil, prompt only if there's no usable symbol at point.

(fn IDENTIFIER)" t)
(autoload 'xref-find-definitions-at-mouse "xref" "\
Find the definition of identifier at or around mouse click.
This command is intended to be bound to a mouse event.

(fn EVENT)" t)
(autoload 'xref-find-references-at-mouse "xref" "\
Find references to the identifier at or around mouse click.
This command is intended to be bound to a mouse event.

(fn EVENT)" t)
(autoload 'xref-mouse-mode "xref" "\
Minor mode to bind Xref commands invoked using the mouse.

See `global-xref-mouse-mode' if you want to enable this minor mode in
all buffers.

This is a minor mode.  If called interactively, toggle the `Xref-Mouse
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `xref-mouse-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-xref-mouse-mode 'globalized-minor-mode t)
(defvar global-xref-mouse-mode nil "\
Non-nil if Global Xref-Mouse mode is enabled.
See the `global-xref-mouse-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-xref-mouse-mode'.")
(custom-autoload 'global-xref-mouse-mode "xref" nil)
(autoload 'global-xref-mouse-mode "xref" "\
Toggle Xref-Mouse mode in all buffers.
With prefix ARG, enable Global Xref-Mouse mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Xref-Mouse mode is enabled in all buffers where `xref-mouse-mode'
would do it.

See `xref-mouse-mode' for more information on Xref-Mouse mode.

(fn &optional ARG)" t)
(autoload 'xref-find-apropos "xref" "\
Find all meaningful symbols that match PATTERN.
The argument has the same meaning as in `apropos'.
See `tags-apropos-additional-actions' for how to augment the
output of this command when the backend is etags.

(fn PATTERN)" t)
 (define-key esc-map "." #'xref-find-definitions)
 (define-key esc-map "," #'xref-go-back)
 (define-key esc-map [?\C-,] #'xref-go-forward)
 (define-key esc-map "?" #'xref-find-references)
 (define-key esc-map [?\C-.] #'xref-find-apropos)
 (define-key ctl-x-4-map "." #'xref-find-definitions-other-window)
 (define-key ctl-x-5-map "." #'xref-find-definitions-other-frame)
(autoload 'xref-references-in-directory "xref" "\
Find all references to SYMBOL in directory DIR.
See `xref-references-in-directory-function' for the implementation.
Return a list of xref values.

(fn SYMBOL DIR)")
(autoload 'xref-matches-in-directory "xref" "\
Find all matches for REGEXP in directory DIR.
Return a list of xref values.
Only files matching some of FILES and none of IGNORES are searched.
FILES is a string with glob patterns separated by spaces.
IGNORES is a list of glob patterns for files to ignore.
If DELIMITED is `symbol', only select matches that span full symbols.

(fn REGEXP FILES DIR IGNORES &optional DELIMITED)")
(autoload 'xref-matches-in-files "xref" "\
Find all matches for REGEXP in FILES.
Return a list of xref values.
FILES must be a list of absolute file names.

See `xref-search-program' and `xref-search-program-alist' for how
to control which program to use when looking for matches.

(fn REGEXP FILES)")

;;; End of scraped data

(provide 'xref-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xref-autoloads.el ends here
