-- Require plugin configs
require("lsc.autopairs")
require("lsc.bufferline")
require("lsc.cmp")
require("lsc.colorscheme")
require("lsc.comment")
require("lsc.gitsigns")
require("lsc.keymaps")
require("lsc.lsp")
require("lsc.lualine")
require("lsc.nvimtree")
require("lsc.options")
require("lsc.plugins")
require("lsc.toggleterm")
