;;; let-completion-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from let-completion.el

(autoload 'let-completion-locals-only-complete "let-completion" "\
Complete at point showing only locally bound candidates.
temporarily restricts completion to variables from enclosing
binding forms for a single invocation.  the local-only table
is captured by the completion ui and persists for the session.

Also see `let-completion-locals-only-mode'." t)
(autoload 'let-completion-mode "let-completion" "\
Enrich Elisp completion with let-binding values.

When enabled, install `let-completion--advice' around
`elisp-completion-at-point'.  When disabled, remove it.

Also see `let-completion-inline-max-width'.

This is a minor mode.  If called interactively, toggle the
`Let-Completion mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `let-completion-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)

;;; End of scraped data

(provide 'let-completion-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; let-completion-autoloads.el ends here
