;;; evil-args-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from evil-args.el

(autoload 'evil-backward-arg "evil-args" "\
Move the cursor backward COUNT arguments.

(fn COUNT)" t)
(autoload 'evil-forward-arg "evil-args" "\
Move the cursor forward COUNT arguments.

(fn COUNT)" t)
 (autoload 'evil-inner-arg "evil-args")
 (autoload 'evil-outer-arg "evil-args")
(autoload 'evil-jump-out-args "evil-args" "\
Move the cursor out of the nearest enclosing matching pairs.

(fn COUNT)" t)

;;; End of scraped data

(provide 'evil-args-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-args-autoloads.el ends here
