;;; embrace-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from embrace.el

(autoload 'embrace-delete "embrace" nil t)
(autoload 'embrace-change "embrace" nil t)
(autoload 'embrace-add "embrace" nil t)
(autoload 'embrace-commander "embrace" nil t)
(autoload 'embrace-LaTeX-mode-hook "embrace")
(autoload 'embrace-org-mode-hook "embrace")
(autoload 'embrace-ruby-mode-hook "embrace")
(autoload 'embrace-emacs-lisp-mode-hook "embrace")

;;; End of scraped data

(provide 'embrace-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; embrace-autoloads.el ends here
