[tools]
age = "latest"
atuin = "latest"
aws-vault = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bat = "0.26.1"
chezmoi = "2.72.0"
claude = "latest"
container = "latest"
difftastic = "latest"
eksctl = "0.230.0"
eza = "latest"
fnox = "latest"
gh = "latest"
herdr = "0.8.2"
hk = "latest"
jj = "0.44.0"
kubectl = "1.37.0"
mkcert = "latest"
neovim = "0.12.5"
pkl = "0.32.1"
ripgrep = "15.2.0"
rust = "stable"
starship = "1.26.0"
teleport-ent = "18"
terraform = "1.16.0"
terragrunt = "1.1.3"
terramate = "0.17.2"
usage = "6.4.1"
uv = "0.12.6"
xh = "0.26.2"
zmx = "0.7.0"
zoxide = "0.10.0"

[settings]
disable_backends = ["vfox"]

[settings.ruby]
compile = false
