[tools]
age = "latest"
atuin = "latest"
aws-vault = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bat = "0.26.1"
chezmoi = "2.70.2"
eksctl = "0.226.0"
fnox = "latest"
gh = "latest"
hk = "latest"
jj = "latest"
kubectl = "1.36.0"
mkcert = "latest"
neovim = "0.12.2"
pkl = "0.31.1"
ripgrep = "15.1.0"
starship = "1.25.1"
terraform = "1.15.2"
terragrunt = "1.0.3"
terramate = "0.17.0"
usage = "3.3.0"
uv = "0.11.7"
xh = "0.25.3"
zoxide = "0.9.9"

[settings.ruby]
compile = false
