[tools]
age = "latest"
bat = "0.26.1"
chezmoi = "2.70.2"
difftastic = "0.68.0"
eksctl = "0.225.0"
fd = "10.4.2"
fnox = "latest"
go = "1.26.2"
goreleaser = "2.15.3"
jj = "0.40.0"
just = "1.50.0"
krew = "0.5.0"
kubectl = "1.35.4"
neovim = "0.12.1"
node = "25.9.0"
pkl = "0.31.1"
protoc = "33.4"
ripgrep = "15.1.0"
ruby = "4.0.3"
rust = "1.95.0"
starship = "1.25.0"
television = "0.15.6"
terraform = "1.14.9"
terragrunt = "1.0.2"
terramate = "0.16.0"
usage = "3.2.0"
uv = "0.11.7"
xh = "0.25.3"
zellij = "0.44.1"
zig = "0.16.0"
zoxide = "0.9.9"

[settings]
[settings.ruby]
compile = false
