;;; yasnippet-capf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from yasnippet-capf.el

(autoload 'yasnippet-capf "yasnippet-capf" "\
Complete with yasnippet at point.
If INTERACTIVE is nil the function acts like a Capf.

(fn &optional INTERACTIVE)" t)

;;; End of scraped data

(provide 'yasnippet-capf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; yasnippet-capf-autoloads.el ends here
