return {}
-- return {
--   {
--     "stevearc/aerial.nvim",
--     keys = {
--       { "<leader>a", ":AerialToggle<cr>", desc = "Toggle Aerial" },
--       { "<leader>sa", ":Telescope aerial<cr>", desc = "Telescope aerial" },
--     },
--     config = function()
--       require("telescope").load_extension("aerial")
--     end,
--   },
-- }
