;; -*- mode: emacs-lisp; lexical-binding: t; coding: utf-8-unix; -*-
;;;###if (or initial-window-system (daemonp))
;;;###allow nil
;;;###deny nil
;;;###date 2026-07-13 21:55:26
(put 'process-environment 'doom t)
(setq process-environment
      (append
       '("_=/usr/bin/emacs" "TERM_PROGRAM=ghostty"
	 "OPAM_LAST_ENV=/home/lsc/.opam/.last-env/env-ef5620bb467ebea57201ddf92964c850-0"
	 "HYPRCURSOR_SIZE=24"
	 "GUM_CONFIRM_SELECTED_FOREGROUND=#c0caf5"
	 "GUM_LOG_SEPARATOR_BACKGROUND=#1a1b26"
	 "USE_GKE_GCLOUD_AUTH_PLUGIN=True"
	 "GUM_FILE_SELECTED_FOREGROUND=#c0caf5"
	 "EMACS_PLUS_NO_PATH_INJECTION=1"
	 "GUM_LOG_PREFIX_BACKGROUND=#1a1b26"
	 "GUM_LOG_MESSAGE_FOREGROUND=#a9b1d6"
	 "GUM_TABLE_BORDER_BACKGROUND=#1a1b26"
	 "GUM_CONFIRM_UNSELECTED_BACKGROUND=#1a1b26"
	 "GUM_WRITE_PLACEHOLDER_BACKGROUND=#1a1b26"
	 "GUM_CONFIRM_UNSELECTED_FOREGROUND=#a9b1d6"
	 "UWSM_FINALIZE_VARNAMES=HYPRLAND_INSTANCE_SIGNATURE HYPRLAND_CMD HYPRCURSOR_THEME HYPRCURSOR_SIZE XCURSOR_SIZE XCURSOR_THEME"
	 "GUM_TABLE_BORDER_FOREGROUND=#444b6a"
	 "MAIL=/var/spool/mail/lsc"
	 "GUM_FILTER_TEXT_BACKGROUND=#1a1b26" "OPAMNOENVNOTICE=true"
	 "GUM_WRITE_CURSOR_LINE_BACKGROUND=#7aa2f7"
	 "GUM_FILE_HEADER_FOREGROUND=#a9b1d6"
	 "GUM_FILE_PERMISSIONS_FOREGROUND=#444b6a"
	 "GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND=#444b6a"
	 "GUM_TABLE_SELECTED_BACKGROUND=#7aa2f7" "GDK_SCALE=1"
	 "GUM_SPIN_SPINNER_FOREGROUND=#7aa2f7"
	 "PATH=/home/lsc/.config/emacs/bin:/home/lsc/.opam/default/bin:/home/lsc/.local/share/mise/installs/age/latest/age:/home/lsc/.local/share/mise/installs/atuin/latest/atuin-x86_64-unknown-linux-musl:/home/lsc/.local/share/mise/installs/aws-vault/latest:/home/lsc/.local/share/mise/installs/awscli/latest/.mise-bins:/home/lsc/.local/share/mise/installs/bat/0.26.1/bat-v0.26.1-x86_64-unknown-linux-musl:/home/lsc/.local/share/mise/installs/chezmoi/2.70.5:/home/lsc/.local/share/mise/installs/difftastic/latest:/home/lsc/.local/share/mise/installs/eksctl/0.227.0:/home/lsc/.local/share/mise/installs/eza/latest:/home/lsc/.local/share/mise/installs/fnox/latest:/home/lsc/.local/share/mise/installs/gh/latest/gh_2.95.0_linux_amd64/bin:/home/lsc/.local/share/mise/installs/hk/latest:/home/lsc/.local/share/mise/installs/jj/0.42.0:/home/lsc/.local/share/mise/installs/kubectl/1.36.2:/home/lsc/.local/share/mise/installs/mkcert/latest:/home/lsc/.local/share/mise/installs/neovim/0.12.2/bin:/home/lsc/.local/share/mise/installs/pkl/0.31.1:/home/lsc/.local/share/mise/installs/ripgrep/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl:/home/lsc/.cargo/bin:/home/lsc/.local/share/mise/installs/starship/1.25.1:/home/lsc/.local/share/mise/installs/teleport-ent/18/bin:/home/lsc/.local/share/mise/installs/terraform/1.15.6:/home/lsc/.local/share/mise/installs/terragrunt/1.0.8:/home/lsc/.local/share/mise/installs/terramate/0.17.1:/home/lsc/.local/share/mise/installs/usage/3.5.2:/home/lsc/.local/share/mise/installs/uv/0.11.23/uv-x86_64-unknown-linux-musl:/home/lsc/.local/share/mise/installs/xh/0.26.1/xh-v0.26.1-x86_64-unknown-linux-musl:/home/lsc/.local/share/mise/installs/zoxide/0.9.9:/home/lsc/.local/bin:/home/lsc/.local/share/mise/shims:/usr/bin:/home/lsc/.local/share/omarchy/bin:/home/lsc/.local/share/mise/shims:/usr/bin:/home/lsc/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/lsc/.local/bin"
	 "GUM_WRITE_END_OF_BUFFER_BACKGROUND=#1a1b26"
	 "GUM_WRITE_END_OF_BUFFER_FOREGROUND=#444b6a"
	 "GDK_BACKEND=wayland,x11,*"
	 "GUM_CONFIRM_PROMPT_BACKGROUND=#1a1b26"
	 "XDG_DATA_DIRS=/usr/local/share:/usr/share:/home/lsc/.nix-profile/share:/nix/var/nix/profiles/default/share"
	 "MISE_SHELL=fish" "GUM_FILTER_SELECTED_FOREGROUND=#c0caf5"
	 "GUM_WRITE_BASE_FOREGROUND=#a9b1d6"
	 "GUM_LOG_LEVEL_BACKGROUND=#1a1b26"
	 "GUM_WRITE_HEADER_BACKGROUND=#1a1b26"
	 "GUM_FILTER_INDICATOR_BACKGROUND=#1a1b26"
	 "GUM_LOG_SEPARATOR_FOREGROUND=#444b6a"
	 "GUM_TABLE_CELL_FOREGROUND=#a9b1d6"
	 "GUM_LOG_VALUE_FOREGROUND=#a9b1d6"
	 "DOCKER_HOST=unix:///run/user/1000/podman/podman.sock"
	 "GUM_FILE_FILE_SIZE_BACKGROUND=#1a1b26"
	 "DEBUGINFOD_URLS=https://debuginfod.archlinux.org "
	 "GUM_TABLE_HEADER_BACKGROUND=#1a1b26"
	 "GUM_WRITE_CURSOR_FOREGROUND=#c0caf5"
	 "XDG_STATE_HOME=/home/lsc/.local/state"
	 "GUM_FILTER_TEXT_FOREGROUND=#a9b1d6" "MANAGERPIDFDID=4240"
	 "ATUIN_SESSION=019f5d095b777a01b387a6fe0e0324c7"
	 "GUM_TABLE_SELECTED_FOREGROUND=#c0caf5"
	 "GUM_INPUT_PROMPT_BACKGROUND=#1a1b26" "QT_IM_MODULE=fcitx"
	 "GUM_CHOOSE_CURSOR_BACKGROUND=#1a1b26" "MOZ_ENABLE_WAYLAND=1"
	 "GUM_PAGER_HELP_FOREGROUND=#444b6a"
	 "GUM_WRITE_PROMPT_FOREGROUND=#a9b1d6"
	 "GUM_FILE_DIRECTORY_BACKGROUND=#1a1b26"
	 "GUM_FILTER_SELECTED_PREFIX_BACKGROUND=#7aa2f7"
	 "FOREGROUND=#a9b1d6" "GUM_LOG_KEY_BACKGROUND=#1a1b26"
	 "HYPRLAND_INSTANCE_SIGNATURE=39d7e209c79d451efab1b21151d5938289da838d_1783960056_39643106"
	 "GUM_PAGER_MATCH_BACKGROUND=#1a1b26"
	 "GUM_CHOOSE_CURSOR_FOREGROUND=#7aa2f7"
	 "GUM_FILTER_PROMPT_BACKGROUND=#1a1b26"
	 "GUM_INPUT_PROMPT_FOREGROUND=#7aa2f7"
	 "GUM_FILTER_MATCH_BACKGROUND=#1a1b26"
	 "OZONE_PLATFORM=wayland"
	 "GUM_WRITE_PROMPT_BACKGROUND=#1a1b26"
	 "RUSTUP_HOME=/home/lsc/.rustup"
	 "GUM_INPUT_PLACEHOLDER_BACKGROUND=#1a1b26"
	 "TERMINFO=/usr/share/terminfo"
	 "GUM_FILTER_PLACEHOLDER_BACKGROUND=#1a1b26"
	 "GUM_SPIN_TITLE_BACKGROUND=#1a1b26"
	 "GUM_CHOOSE_ITEM_FOREGROUND=#a9b1d6"
	 "GUM_WRITE_HEADER_FOREGROUND=#a9b1d6"
	 "GUM_LOG_LEVEL_FOREGROUND=#7aa2f7"
	 "GHOSTTY_RESOURCES_DIR=/usr/share/ghostty"
	 "SDL_IM_MODULE=fcitx" "GUM_WRITE_BASE_BACKGROUND=#1a1b26"
	 "GUM_FILTER_INDICATOR_FOREGROUND=#7aa2f7"
	 "XDG_CACHE_HOME=/home/lsc/.cache"
	 "UWSM_WAIT_VARNAMES=HYPRLAND_INSTANCE_SIGNATURE"
	 "QT_QPA_PLATFORM=wayland;xcb"
	 "STARSHIP_SESSION_KEY=3082026834206997"
	 "GUM_LOG_TIME_BACKGROUND=#1a1b26"
	 "GUM_CHOOSE_SELECTED_BACKGROUND=#7aa2f7"
	 "GUM_LOG_MESSAGE_BACKGROUND=#1a1b26" "MANAGERPID=1225"
	 "GUM_PAGER_LINE_NUMBER_BACKGROUND=#1a1b26"
	 "GUM_INPUT_CURSOR_BACKGROUND=#1a1b26"
	 "GUM_PAGER_FOREGROUND=#a9b1d6"
	 "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0"
	 "GUM_CHOOSE_HEADER_BACKGROUND=#1a1b26" "TMPDIR=/tmp/"
	 "GUM_TABLE_CELL_BACKGROUND=#1a1b26"
	 "GUM_INPUT_HEADER_BACKGROUND=#1a1b26"
	 "GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND=#444b6a"
	 "GUM_PAGER_HELP_BACKGROUND=#1a1b26"
	 "NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"
	 "GUM_FILTER_HEADER_BACKGROUND=#1a1b26" "STARSHIP_SHELL=fish"
	 "MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/wayland-wm@hyprland.desktop.service/memory.pressure"
	 "GUM_FILTER_CURSOR_TEXT_BACKGROUND=#1a1b26"
	 "GUM_PAGER_BACKGROUND=#1a1b26"
	 "GUM_CHOOSE_HEADER_FOREGROUND=#a9b1d6"
	 "GUM_INPUT_CURSOR_FOREGROUND=#c0caf5"
	 "GUM_TABLE_HEADER_FOREGROUND=#a9b1d6"
	 "RUSTUP_TOOLCHAIN=1.96.0" "CARGO_HOME=/home/lsc/.cargo"
	 "_JAVA_AWT_WM_NONREPARENTING=1"
	 "TELEPORT_ADD_KEYS_TO_AGENT=no"
	 "GITHUB_TOKEN=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"
	 "LANG=en_US.UTF-8" "GUM_PAGER_MATCH_FOREGROUND=#7aa2f7"
	 "GUM_WRITE_LINE_NUMBER_FOREGROUND=#444b6a"
	 "GHOSTTY_SHELL_FEATURES=cursor:blink,path,ssh-env,ssh-terminfo,sudo,title"
	 "ATUIN_TMUX_POPUP=false" "MOTD_SHOWN=pam"
	 "QT_STYLE_OVERRIDE=kvantum"
	 "GUM_FILE_HEADER_BACKGROUND=#1a1b26"
	 "TERMINAL=xdg-terminal-exec"
	 "GUM_FILE_CURSOR_BACKGROUND=#1a1b26"
	 "GUM_PAGER_LINE_NUMBER_FOREGROUND=#444b6a"
	 "OPAM_SWITCH_PREFIX=/home/lsc/.opam/default"
	 "GUM_FILTER_PLACEHOLDER_FOREGROUND=#444b6a"
	 "SYSTEMD_EXEC_PID=1419"
	 "GUM_FILTER_SELECTED_BACKGROUND=#7aa2f7"
	 "GUM_FILTER_UNSELECTED_PREFIX_BACKGROUND=#1a1b26"
	 "MANPATH=:/home/lsc/.opam/default/man"
	 "GUM_PAGER_MATCH_HIGH_FOREGROUND=#7aa2f7"
	 "GUM_FILE_SYMLINK_FOREGROUND=#a9b1d6"
	 "GUM_INPUT_HEADER_FOREGROUND=#a9b1d6"
	 "GUM_FILE_CURSOR_FOREGROUND=#c0caf5"
	 "GUM_WRITE_CURSOR_LINE_NUMBER_BACKGROUND=#1a1b26"
	 "ATUIN_SHLVL=1" "GUM_SPIN_TITLE_FOREGROUND=#a9b1d6"
	 "LOGNAME=lsc" "GUM_FILTER_MATCH_FOREGROUND=#7aa2f7"
	 "NIX_PROFILES=/nix/var/nix/profiles/default /home/lsc/.nix-profile"
	 "GUM_FILE_FILE_FOREGROUND=#a9b1d6"
	 "OCAMLTOP_INCLUDE_PATH=/home/lsc/.opam/default/lib/toplevel"
	 "GUM_LOG_PREFIX_FOREGROUND=#a9b1d6"
	 "GUM_LOG_KEY_FOREGROUND=#a9b1d6" "EDITOR=nvim"
	 "GUM_CHOOSE_SELECTED_FOREGROUND=#c0caf5" "XCURSOR_SIZE=24"
	 "GUM_WRITE_CURSOR_LINE_FOREGROUND=#a9b1d6"
	 "HL_INITIAL_WORKSPACE_TOKEN=41556250-8063-414d-8a99-5c59465210aa"
	 "ELECTRON_OZONE_PLATFORM_HINT=wayland"
	 "DESKTOP_SESSION=omarchy" "BORDER_FOREGROUND=#7aa2f7"
	 "GUM_WRITE_LINE_NUMBER_BACKGROUND=#1a1b26"
	 "XMODIFIERS=@im=fcitx"
	 "GUM_FILE_PERMISSIONS_BACKGROUND=#1a1b26"
	 "GUM_FILE_DIRECTORY_FOREGROUND=#a9b1d6"
	 "GUM_PAGER_MATCH_HIGH_BACKGROUND=#1a1b26"
	 "GUM_FILE_SYMLINK_BACKGROUND=#1a1b26"
	 "MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA="
	 "OMARCHY_PATH=/home/lsc/.local/share/omarchy"
	 "GUM_INPUT_PLACEHOLDER_FOREGROUND=#444b6a"
	 "XDG_CONFIG_HOME=/home/lsc/.config"
	 "XCOMPOSEFILE=~/.XCompose"
	 "GUM_FILTER_PROMPT_FOREGROUND=#7aa2f7"
	 "GUM_LOG_TIME_FOREGROUND=#444b6a" "INPUT_METHOD=fcitx"
	 "GUM_CONFIRM_SELECTED_BACKGROUND=#7aa2f7"
	 "GUM_WRITE_PLACEHOLDER_FOREGROUND=#444b6a"
	 "XDG_DATA_HOME=/home/lsc/.local/share"
	 "GUM_FILE_SELECTED_BACKGROUND=#7aa2f7"
	 "BORDER_BACKGROUND=#1a1b26"
	 "GUM_CHOOSE_ITEM_BACKGROUND=#1a1b26"
	 "GUM_FILTER_CURSOR_TEXT_FOREGROUND=#c0caf5"
	 "GUM_LOG_VALUE_BACKGROUND=#1a1b26"
	 "GUM_FILTER_SELECTED_PREFIX_FOREGROUND=#c0caf5"
	 "GUM_FILE_FILE_BACKGROUND=#1a1b26" "BACKGROUND=#1a1b26"
	 "GUM_CONFIRM_PROMPT_FOREGROUND=#7aa2f7"
	 "GUM_SPIN_SPINNER_BACKGROUND=#1a1b26"
	 "TERM_PROGRAM_VERSION=1.3.1-arch2"
	 "XDG_MENU_PREFIX=hyprland-"
	 "GUM_FILE_FILE_SIZE_FOREGROUND=#444b6a"
	 "XDG_CONFIG_DIRS=/etc/xdg"
	 "HYPRLAND_CMD=Hyprland --watchdog-fd 4" "COLORTERM=truecolor"
	 "GUM_FILTER_HEADER_FOREGROUND=#a9b1d6"
	 "OCAML_TOPLEVEL_PATH=/home/lsc/.opam/default/lib/toplevel"
	 "GHOSTTY_BIN_DIR=/usr/bin"
	 "GUM_WRITE_CURSOR_BACKGROUND=#1a1b26"
	 "CAML_LD_LIBRARY_PATH=/home/lsc/.opam/default/lib/stublibs:/home/lsc/.opam/default/lib/ocaml/stublibs:/home/lsc/.opam/default/lib/ocaml"
	 "SHELL=/bin/fish")
       (default-value 'process-environment))
      exec-path
      (append (split-string (getenv "PATH") path-separator t)
	      (list exec-directory))
      shell-file-name
      (or (getenv "SHELL") (default-value 'shell-file-name)))
