;;; evil-textobj-anyblock-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from evil-textobj-anyblock.el

 (autoload 'evil-textobj-anyblock-inner-block "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-a-block "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-forward-open-block-start "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-forward-open-block-end "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-forward-close-block-start "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-forward-close-block-end "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-backward-open-block-start "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-backward-open-block-end "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-backward-close-block-start "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-backward-close-block-end "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-forward-any-block-start "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-forward-any-block-end "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-backward-any-block-start "evil-textobj-anyblock" nil t)
 (autoload 'evil-textobj-anyblock-backward-any-block-end "evil-textobj-anyblock" nil t)

;;; End of scraped data

(provide 'evil-textobj-anyblock-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-textobj-anyblock-autoloads.el ends here
