;;; quickrun-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from quickrun.el

(autoload 'quickrun-set-default "quickrun" "\
Set `key' as default key in programing language `lang'.

(fn LANG KEY)")
(autoload 'quickrun-select-default "quickrun" "\
Update the default." t)
(autoload 'quickrun-add-command "quickrun" "\
Not documented.

(fn KEY ALIST &key DEFAULT MODE OVERRIDE)")
(function-put 'quickrun-add-command 'lisp-indent-function 'defun)
(autoload 'quickrun "quickrun" "\
Run commands quickly for current buffer.

With universal prefix argument(C-u), select command-key,
With double prefix argument(C-u C-u), run in compile-only-mode.

(fn &rest PLIST)" t)
(autoload 'quickrun-select "quickrun" "\
Run commands after selecting the backend." t)
(autoload 'quickrun-with-arg "quickrun" "\
Run commands quickly for current buffer with arguments.

(fn ARG)" t)
(autoload 'quickrun-region "quickrun" "\
Run commands with specified region.

(fn START END)" t)
(autoload 'quickrun-replace-region "quickrun" "\
Run commands with specified region and replace.

(fn START END)" t)
(autoload 'quickrun-eval-print "quickrun" "\
Run commands with specified region and replace.

(fn START END)" t)
(autoload 'quickrun-compile-only "quickrun" "\
Exec only compilation." t)
(autoload 'quickrun-compile-only-select "quickrun" "\
Run commands after selecting the backend." t)
(autoload 'quickrun-shell "quickrun" "\
Run commands in shell for interactive programs." t)
(autoload 'quickrun-autorun-mode "quickrun" "\
`quickrun' after saving buffer.

This is a minor mode.  If called interactively, toggle the
`Quickrun-Autorun mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `quickrun-autorun-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'anything-quickrun "quickrun" "\
Run quickrun with `anything'." t)
(autoload 'helm-quickrun "quickrun" "\
Run quickrun with `helm'." t)

;;; End of scraped data

(provide 'quickrun-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; quickrun-autoloads.el ends here
