[tools]
bat = "0.24.0"
cue = "0.9.0-0.dev"
difftastic = "0.58.0"
eksctl = "0.180.0"
exa = "0.10.1"
fd = "10.1.0"
fzf = "0.52.1"
go = "1.22.3"
just = "1.28.0"
kubectl = "1.30.1"
neovim = "0.10.0"
node = "22.2.0"
opentofu = "1.7.2"
pkl = "0.25.3"
python = "3.11"
ripgrep = "latest"
ruby = "3.3.1"
rust = "latest"
starship = "1.19.0"
terraform = "1.8.4"
terragrunt = "0.58.12"
terramate = "0.8.4"
usage = "0.3.0"
zig = "latest"
lua = "5.4.6"
