[tools]
bat = "latest"
cue = "latest"
fd = "latest"
go = "latest"
kubectl = "latest"
neovim = "latest"
opentofu = "latest"
ripgrep = "latest"
rust = "latest"
terraform = "latest"
terragrunt = "latest"
terramate = "latest"
usage = "latest"
terramate = "0.5.0"
