[tools]
bat = "latest"
fd = "latest"
golang = "1.21.4"
kubectl = "1.27.0"
neovim = "0.9.5"
ripgrep = "latest"
rust = "1.74.1"
terraform = "1.3.9"
terragrunt = "0.54.9"
opentofu = "1.6.1"
cue = "0.7.0"
go = "1.22"
yarn = "1.22.19"
