[tools]
bat = "latest"
cue = "0.7.0"
fd = "latest"
go = "1.22"
golang = "1.21.4"
kubectl = "1.27.0"
neovim = "0.9.5"
opentofu = "1.6.1"
ripgrep = "latest"
rust = "1.74.1"
terraform = "1.3.9"
terragrunt = "0.54.9"
usage = "latest"
