[tools]
cue = "0.9.1"
difftastic = "0.58.0"
eksctl = "0.180.0"
fd = "10.1.0"
fzf = "0.52.1"
go = "1.22.3"
just = "1.28.0"
kubectl = "1.30.1"
lua = "5.1.5"
node = "22.2.0"
pkl = "0.25.3"
python = "3.12.4"
ripgrep = "14.1.0"
ruby = "3.3.1"
rust = "1.79.0"
starship = "1.19.0"
terraform = "1.8.4"
terragrunt = "0.58.12"
terramate = "0.8.4"
usage = "0.3.0"
zig = "0.13.0"
java = "zulu-21.30.15"
krew = "0.4.4"
glab = "latest"
opentofu = "1.8.3"
