[tools]
bat = "latest"
cue = "latest"
difftastic = "latest"
eksctl = "latest"
exa = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
just = "latest"
kubectl = "latest"
neovim = "stable"
node = "latest"
opentofu = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
terragrunt = "latest"
terramate = "latest"
usage = "latest"
zig = "latest"
python = "3.12"
ruby = "3.3.1"
