[tools]
bat = "latest"
cue = "latest"
difftastic = "latest"
direnv = "2.34.0"
eksctl = "latest"
exa = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
just = "latest"
kubectl = "latest"
neovim = "0.10.0"
node = "latest"
opentofu = "latest"
ripgrep = "latest"
ruby = "3.3.1"
rust = "latest"
starship = "latest"
terraform = "latest"
terragrunt = "latest"
terramate = "latest"
usage = "latest"
zig = "latest"
pkl = "0.25.3"
python = "3.11"
