[tools]
bat = "0.24.0"
cue = "0.9.1"
difftastic = "0.58.0"
eksctl = "0.180.0"
eza = "0.20.5"
fd = "10.1.0"
fzf = "0.52.1"
glab = "latest"
go = ["1.23", "1.22", "1.21", "1.19"]
java = "zulu-21.30.15"
just = "1.28.0"
krew = "0.4.4"
kubectl = "1.30.1"
lua = "5.1.5"
node = "22.2.0"
opentofu = "1.8.3"
pkl = "0.27.0"
protoc = "latest"
python = ["3.11", "3.10", "3.12", "3.13"]
ripgrep = "14.1.0"
ruby = "3.3.1"
rust = "stable"
starship = "1.19.0"
terraform = ["1.3", "1.8.4", "1.5.5"]
terragrunt = ["0.58.12", "0.68.3"]
terramate = "0.8.4"
usage = "0.3.0"
zellij = "0.41.1"
zig = ["0.13.0", "master"]
zoxide = "latest"
